import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { toast } from 'sonner';
import Navbar from '../components/Navbar.jsx';
import { configCategories } from '../utils/autoexecData';

export default function Autoexec() {
  const { t } = useTranslation();

  // Estado inicial dinámico basado en los defaults
  const [config, setConfig] = useState(() => {
    const defaults = {};
    configCategories.forEach(cat => {
      cat.items.forEach(item => {
        defaults[item.id] = item.default;
      });
    });
    return defaults;
  });

  const handleChange = (id, value) => {
    setConfig(prev => ({ ...prev, [id]: value }));
  };

  const generateFileContent = () => {
    let content = "// Generated by CS:GO Cloud Autoexec Builder\n\n";
    
    configCategories.forEach(cat => {
      content += `// --- ${t(cat.title).toUpperCase()} ---\n`;
      cat.items.forEach(item => {
        const val = item.type === 'checkbox' ? (config[item.id] ? 1 : 0) : config[item.id];
        content += `${item.cmd} "${val}"\n`;
      });
      content += "\n";
    });

    content += 'host_writeconfig;\n';
    content += 'echo "Autoexec loaded successfully!";\n';
    return content;
  };

  const handleDownload = () => {
    const element = document.createElement("a");
    const file = new Blob([generateFileContent()], {type: 'text/plain'});
    element.href = URL.createObjectURL(file);
    element.download = "autoexec.cfg";
    document.body.appendChild(element); // Requerido para Firefox
    element.click();
    document.body.removeChild(element);
    toast.success(t('download_success'));
  };

  return (
    <div style={{ minHeight: '100vh', background: '#111827', color: 'white' }}>
      <Navbar />
      <div style={{ padding: '30px 20px', maxWidth: '900px', margin: '0 auto' }}>
        
        <div style={{ textAlign: 'center', marginBottom: '40px' }}>
            <h2 style={{ fontSize: '2.5rem', margin: '0 0 10px 0', color: '#eab308' }}>⚙️ {t('autoexec_title')}</h2>
            <p style={{ color: '#9ca3af', fontSize: '1.1rem' }}>{t('autoexec_subtitle')}</p>
        </div>

        <div style={{ display: 'grid', gap: '30px' }}>
            {configCategories.map(cat => (
                <div key={cat.id} style={{ background: '#1f2937', padding: '25px', borderRadius: '12px', border: '1px solid #374151' }}>
                    <h3 style={{ borderBottom: '1px solid #374151', paddingBottom: '10px', marginBottom: '20px', color: '#eab308' }}>
                        {t(cat.title)}
                    </h3>
                    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '20px' }}>
                        {cat.items.map(item => (
                            <div key={item.id} style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
                                <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.9em' }}>
                                    <label>{t(item.label)}</label>
                                    <span style={{ color: '#9ca3af', fontFamily: 'monospace' }}>
                                        {item.type === 'checkbox' ? (config[item.id] ? 'ON' : 'OFF') : config[item.id]}
                                    </span>
                                </div>
                                
                                {item.type === 'range' && (
                                    <input 
                                        type="range" 
                                        min={item.min} max={item.max} step={item.step}
                                        value={config[item.id]} 
                                        onChange={e => handleChange(item.id, e.target.value)}
                                        style={{ accentColor: '#eab308', width: '100%' }}
                                    />
                                )}

                                {item.type === 'number' && (
                                    <input 
                                        type="number"
                                        min={item.min} max={item.max}
                                        value={config[item.id]}
                                        onChange={e => handleChange(item.id, e.target.value)}
                                        style={{ padding: '8px', borderRadius: '6px', border: '1px solid #4b5563', background: '#111827', color: 'white' }}
                                    />
                                )}

                                {item.type === 'checkbox' && (
                                    <div style={{ marginTop: '5px' }}>
                                        <input 
                                            type="checkbox"
                                            checked={config[item.id]}
                                            onChange={e => handleChange(item.id, e.target.checked)}
                                            style={{ accentColor: '#eab308', transform: 'scale(1.2)' }}
                                        />
                                    </div>
                                )}
                                
                                {item.type === 'select' && (
                                    <select 
                                        value={config[item.id]} 
                                        onChange={e => handleChange(item.id, e.target.value)}
                                        style={{ padding: '8px', borderRadius: '6px', border: '1px solid #4b5563', background: '#111827', color: 'white' }}
                                    >
                                        {item.options.map(opt => (
                                            <option key={opt.value} value={opt.value}>{opt.label}</option>
                                        ))}
                                    </select>
                                )}
                            </div>
                        ))}
                    </div>
                </div>
            ))}
        </div>

        <div style={{ marginTop: '40px', textAlign: 'center' }}>
            <button 
                onClick={handleDownload}
                style={{ 
                    background: '#eab308', color: 'black', 
                    padding: '15px 40px', fontSize: '1.2rem', 
                    borderRadius: '8px', border: 'none', 
                    fontWeight: 'bold', cursor: 'pointer',
                    boxShadow: '0 4px 15px rgba(234, 179, 8, 0.4)'
                }}
            >
                💾 {t('download_cfg')}
            </button>
            <p style={{ marginTop: '15px', color: '#6b7280', fontSize: '0.9em' }}>
                {t('cfg_instructions')}
            </p>
        </div>

      </div>
    </div>
  );
}